version: "2"

services:
  app-golang:
    build: golang-server/.
    ports:
      - "80:80"
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
  app-python:
    build: python-server/.
    links:
      - redis
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis:6379
  redis:
    image: redis:alpine
